### ISSUE TITLE
Fix README.md

### ISSUE THREAD

**Issue by iemafzalhassan** [iemafzalhassan/Git_for_DevOps#2]
Please fix README.md

**Comment by lowkeydanish** [comment]
Please i would like to work on this issue.

**Comment by lowkeydanish** [comment]
Hi afzal. I have changed the table of content in the feature branch.
Kindly review it.

**Comment by iemafzalhassan** [comment]
#### Ya HI @Danish-0710 It,s looking well structured. Thnkew so much for contributing in the project.

###### Please do merge into main branch
